"""
Forecasting Pipeline Executor
Handles data fetching and pipeline execution
"""
import yfinance as yf
import pandas as pd
from typing import Dict, Any, List
from datetime import datetime, timedelta

from app.models.schemas import RouterAIOutput
from app.pipelines.forecasting.pipeline import ForecastingPipeline, build_forecast_request
from app.services.chart_generator import generate_chart


async def execute_forecast(
    router_output: RouterAIOutput,
    user_id: str
) -> Dict[str, Any]:
    """
    Execute forecasting pipeline based on router output.
    """
    try:
        # 1. Extract parameters
        entities = router_output.entities.assets
        if not entities or entities == ["__ALL__"]:
            return {
                "success": False,
                "text": "Please specify a stock symbol to forecast (e.g., 'Forecast AAPL').",
                "data": {},
                "visualization": None
            }
        
        symbol = entities[0]
        horizon_days = 30
        
        # Parse time range for horizon
        if router_output.entities.time_range:
            tr = router_output.entities.time_range
            if tr.type == "relative" and tr.unit in ["days", "weeks", "months"]:
                if tr.unit == "weeks":
                    horizon_days = tr.value * 7
                elif tr.unit == "months":
                    horizon_days = tr.value * 30
                else:
                    horizon_days = tr.value
        
        # Limit horizon
        horizon_days = min(max(horizon_days, 7), 365)
        
        # 2. Fetch historical data (2 years for good seasonality)
        start_date = (datetime.now() - timedelta(days=730)).strftime('%Y-%m-%d')
        ticker = yf.Ticker(symbol)
        hist = ticker.history(start=start_date)
        
        if hist.empty:
            return {
                "success": False,
                "text": f"Could not fetch historical data for {symbol}.",
                "data": {},
                "visualization": None
            }
        
        # Prepare dataframe for Prophet (ds, y)
        df = hist.reset_index()[['Date', 'Close']]
        df.columns = ['ds', 'y']
        # Remove timezone info if present
        df['ds'] = df['ds'].dt.tz_localize(None)
        
        # 3. Build request
        request = build_forecast_request(
            entity=symbol,
            metric="Close Price",
            horizon_periods=horizon_days,
            horizon_unit="days"
        )
        
        # 4. Run pipeline
        pipeline = ForecastingPipeline()
        result = pipeline.run_forecast(request, df)
        
        # 5. Format for response
        chart_data = _format_chart_data(result, symbol)
        image_base64 = generate_chart("line_chart", chart_data)
        
        return {
            "success": True,
            "text": "",  # Will be generated by Explanation AI
            "data": result,
            "visualization": {
                "type": "line_chart",
                "chart_data": chart_data,
                "image_base64": image_base64
            }
        }
        
    except Exception as e:
        print(f"Forecasting error: {e}")
        return {
            "success": False,
            "text": f"Error generating forecast: {str(e)}",
            "data": {"error": str(e)},
            "visualization": None
        }


def _format_chart_data(result: Dict[str, Any], symbol: str) -> Dict[str, Any]:
    """Format forecast result for chart generator."""
    forecast_list = result.get("forecast", [])
    
    # Extract data points
    data_points = []
    for item in forecast_list:
        data_points.append({
            "date": item["ds"],
            "close": item["yhat"],
            "lower": item["yhat_lower"],
            "upper": item["yhat_upper"]
        })
    
    return {
        "symbol": symbol,
        "data_points": data_points,
        "is_forecast": True
    }
